name: kichkintoy
description: "Maktabgacha ta'lim platformasi - Kichkintoy Connect"
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State management
  flutter_riverpod: ^2.6.1

  # Network va saqlash
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  web_socket_channel: ^3.0.1

  # Animatsiyalar va o'yinlar
  confetti: ^0.8.0

  # Audio player
  audioplayers: ^6.1.0

  # Grafiklar
  fl_chart: ^0.69.0

  # Forma va validatsiya
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/
